networks:
  dev:


services:
  postgresql:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - dev
    env_file:
      - .env
  backend:
    build:
      context: .
    networks:
      - dev
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    command: bash -c "cd .. && alembic upgrade head && cd /job_exchange/src && python -m main"
    env_file:
      - .env
  frontend:
    build:
      context: ../myBoloto/.
    networks:
      - dev
    ports:
      - "3000:3000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8100:8100"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
