"""job table modified

Revision ID: ba63dfb0f408
Revises: c41085c5803b
Create Date: 2024-07-18 11:14:59.544456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba63dfb0f408'
down_revision: Union[str, None] = 'c41085c5803b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('jobs_job_provider_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'job_provider')
    op.drop_table('job_providers')
    op.add_column('jobs', sa.Column('organization_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'jobs', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_provider', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_job_provider_fkey', 'jobs', 'job_providers', ['job_provider'], ['id'])
    op.drop_column('jobs', 'organizations')
    op.create_table('job_providers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='job_providers_pkey')
    )
    op.drop_table('organizations')
    # ### end Alembic commands ###
