"""Create Plase table

Revision ID: 0f6fb4fb0baa
Revises: 
Create Date: 2024-07-11 16:18:55.799441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '0f6fb4fb0baa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    job_response_type = ENUM('SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='jobresponsetype')
    job_response_type.create(op.get_bind())
    job_status_schema = ENUM('DRAFT', 'CRATED', 'ANDER_REVIEW', 'COMPLETED', 'CLOSED', name='jobstatusschema')
    job_status_schema.create(op.get_bind())
    job_type_schema = ENUM('HOURLY_PAY', 'SALARY', name='jobtypeschema')
    job_type_schema.create(op.get_bind())
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place')
    # ### end Alembic commands ###
