"""create transaction table

Revision ID: d352af3bd3d8
Revises: 61f714575ba2
Create Date: 2024-07-25 15:49:55.500427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'd352af3bd3d8'
down_revision: Union[str, None] = '61f714575ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'CANCELED', 'PENDING', name='transactionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_job_association', sa.Column('response_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='jobresponsetype'), nullable=False))
    op.drop_column('user_job_association', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_job_association', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('user_job_association', 'response_status')
    op.drop_table('user_transactions')
    job_response_type = ENUM(name='jobresponsetype')
    job_response_type.drop(op.get_bind())
    # ### end Alembic commands ###
