"""modify Notifications table

Revision ID: b92e8cdb2979
Revises: 031608d4869a
Create Date: 2024-09-16 09:31:29.547512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92e8cdb2979'
down_revision: Union[str, None] = '031608d4869a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.alter_column('notifications', 'notification_data',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'notification_data',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###
