"""create table user data

Revision ID: ed4fd78775d6
Revises: 2f703af97866
Create Date: 2024-09-15 22:07:06.718984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed4fd78775d6"
down_revision: Union[str, None] = "2f703af97866"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("surname", sa.String(length=50), nullable=False),
        sa.Column("patronymic", sa.String(length=50), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("citizenship", sa.String(length=50), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("passport_data", sa.CHAR(length=10), nullable=False),
        sa.Column("snils", sa.CHAR(length=11), nullable=False),
        sa.Column("medical_book", sa.Boolean(), nullable=False),
        sa.Column("is_self_employed", sa.Boolean(), nullable=False),
        sa.Column("work_experience", sa.String(length=400), nullable=True),
        sa.Column("activity_type", sa.String(length=50), nullable=True),
        sa.Column("contraindications", sa.String(length=200), nullable=True),
        sa.Column("about", sa.String(length=400), nullable=True),
        sa.Column("education", sa.String(length=400), nullable=True),
        sa.Column("driver_license", sa.String(length=100), nullable=True),
        sa.Column("languages", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_data")
    # ### end Alembic commands ###
