"""the user and job tables are supplemented with columns, create status column in user_job_association

Revision ID: ebc72e5e4b98
Revises: 3e0cfbe4a0d7
Create Date: 2024-07-23 09:22:16.281583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc72e5e4b98'
down_revision: Union[str, None] = '3e0cfbe4a0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['owner_id'], ['id'])
    op.add_column('user_job_association', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_job_association', 'status')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_column('jobs', 'owner_id')
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
