"""assosiated tables updated

Revision ID: 7fda3cde2621
Revises: e14351627a04
Create Date: 2024-07-15 13:55:46.273490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fda3cde2621'
down_revision: Union[str, None] = 'e14351627a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_attribute_association', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_attribute_association', 'attribute_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_job_association', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_job_association', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_job_association', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_job_association', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_attribute_association', 'attribute_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_attribute_association', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
