"""created table Job Providers

Revision ID: c41085c5803b
Revises: 7fda3cde2621
Create Date: 2024-07-18 10:41:31.206734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41085c5803b'
down_revision: Union[str, None] = '7fda3cde2621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.add_column('jobs', sa.Column('job_provider', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'jobs', 'job_providers', ['job_provider'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'job_provider')
    op.drop_column('jobs', 'started_at')
    op.drop_table('job_providers')
    # ### end Alembic commands ###
