"""job table modified

Revision ID: 7928962fd780
Revises: 0ed5129afa45
Create Date: 2024-07-29 21:14:11.064579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7928962fd780'
down_revision: Union[str, None] = '0ed5129afa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_status_id', table_name='jobs')
    op.drop_index('ix_jobs_type_id', table_name='jobs')
    op.drop_constraint('jobs_status_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_type_id_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'type_id')
    op.drop_column('jobs', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('jobs_type_id_fkey', 'jobs', 'job_types', ['type_id'], ['id'])
    op.create_foreign_key('jobs_status_id_fkey', 'jobs', 'job_status', ['status_id'], ['id'])
    op.create_index('ix_jobs_type_id', 'jobs', ['type_id'], unique=False)
    op.create_index('ix_jobs_status_id', 'jobs', ['status_id'], unique=False)
    # ### end Alembic commands ###
