"""create index

Revision ID: 192ca3ab8410
Revises: d352af3bd3d8
Create Date: 2024-07-26 10:32:14.646759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192ca3ab8410'
down_revision: Union[str, None] = 'd352af3bd3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_transactions_user_id'), 'user_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_transactions_user_id'), table_name='user_transactions')
    # ### end Alembic commands ###
