"""job model added fields 'created at' and 'finished at'

Revision ID: 23d58edce0fa
Revises: 288692f7d383
Create Date: 2024-07-15 11:21:15.041852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23d58edce0fa'
down_revision: Union[str, None] = '288692f7d383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('jobs', sa.Column('finished_at', sa.DateTime(), nullable=False))
    op.drop_column('jobs', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('period', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'finished_at')
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
