"""update user table

Revision ID: 031608d4869a
Revises: ed4fd78775d6
Create Date: 2024-09-15 22:56:41.173892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031608d4869a'
down_revision: Union[str, None] = 'ed4fd78775d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
