"""job table modified

Revision ID: e813432586f3
Revises: ba63dfb0f408
Create Date: 2024-07-18 13:25:25.887876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e813432586f3'
down_revision: Union[str, None] = 'ba63dfb0f408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_address', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_address')
    # ### end Alembic commands ###
