"""job table modified

Revision ID: 9992a4e63b8b
Revises: 1980e6cf9a0f
Create Date: 2024-07-24 15:05:59.034187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9992a4e63b8b'
down_revision: Union[str, None] = '1980e6cf9a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('type', sa.Uuid(), nullable=False))
    op.add_column('jobs', sa.Column('city', sa.Uuid(), nullable=False))
    op.add_column('jobs', sa.Column('job_location', sa.String(length=400), nullable=False))
    op.execute("""
            ALTER TABLE jobs
            ALTER COLUMN status 
            SET DATA TYPE uuid 
            USING status::uuid;
        """)
    op.create_index(op.f('ix_jobs_city'), 'jobs', ['city'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.drop_constraint('jobs_location_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'job_types', ['type'], ['id'])
    op.create_foreign_key(None, 'jobs', 'places', ['city'], ['id'])
    op.create_foreign_key(None, 'jobs', 'job_status', ['status'], ['id'])
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_location_fkey', 'jobs', 'places', ['location'], ['id'])
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_city'), table_name='jobs')
    op.execute("""
            ALTER TABLE jobs
            ALTER COLUMN status 
            SET DATA TYPE VARCHAR(50)
            USING status::VARCHAR;
        """)
    op.drop_column('jobs', 'job_location')
    op.drop_column('jobs', 'city')
    op.drop_column('jobs', 'type')
    # ### end Alembic commands ###
