"""create cascade delete in user-job relationship

Revision ID: 2f703af97866
Revises: d4f28b6e0a95
Create Date: 2024-07-31 15:13:45.718693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f703af97866'
down_revision: Union[str, None] = 'd4f28b6e0a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_job_association_job_id_fkey', 'user_job_association', type_='foreignkey')
    op.drop_constraint('user_job_association_user_id_fkey', 'user_job_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_job_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_job_association', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_job_association', type_='foreignkey')
    op.drop_constraint(None, 'user_job_association', type_='foreignkey')
    op.create_foreign_key('user_job_association_user_id_fkey', 'user_job_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_job_association_job_id_fkey', 'user_job_association', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
