"""job table modified

Revision ID: 63f36a90c868
Revises: 192ca3ab8410
Create Date: 2024-07-29 10:26:27.190858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f36a90c868'
down_revision: Union[str, None] = '192ca3ab8410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status_id', sa.Uuid(), nullable=False))
    op.add_column('jobs', sa.Column('type_id', sa.Uuid(), nullable=False))
    op.add_column('jobs', sa.Column('action_type_id', sa.Uuid(), nullable=False))
    op.add_column('jobs', sa.Column('city_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_jobs_city', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_type', table_name='jobs')
    op.create_index(op.f('ix_jobs_city_id'), 'jobs', ['city_id'], unique=False)
    op.create_index(op.f('ix_jobs_status_id'), 'jobs', ['status_id'], unique=False)
    op.create_index(op.f('ix_jobs_type_id'), 'jobs', ['type_id'], unique=False)
    op.drop_constraint('jobs_type_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_status_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_action_type_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_city_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'job_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'places', ['city_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'action_types', ['action_type_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'job_types', ['type_id'], ['id'])
    op.drop_column('jobs', 'type')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'action_type')
    op.drop_column('jobs', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('city', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('action_type', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('status', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('type', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_city_fkey', 'jobs', 'places', ['city'], ['id'])
    op.create_foreign_key('jobs_action_type_fkey', 'jobs', 'action_types', ['action_type'], ['id'])
    op.create_foreign_key('jobs_status_fkey', 'jobs', 'job_status', ['status'], ['id'])
    op.create_foreign_key('jobs_type_fkey', 'jobs', 'job_types', ['type'], ['id'])
    op.drop_index(op.f('ix_jobs_type_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_city_id'), table_name='jobs')
    op.create_index('ix_jobs_type', 'jobs', ['type'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_city', 'jobs', ['city'], unique=False)
    op.drop_column('jobs', 'city_id')
    op.drop_column('jobs', 'action_type_id')
    op.drop_column('jobs', 'type_id')
    op.drop_column('jobs', 'status_id')
    # ### end Alembic commands ###
