"""job table modified

Revision ID: 61f714575ba2
Revises: 9992a4e63b8b
Create Date: 2024-07-24 16:09:49.449538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f714575ba2'
down_revision: Union[str, None] = '9992a4e63b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
