"""create tables job_types & job_status

Revision ID: 1980e6cf9a0f
Revises: ebc72e5e4b98
Create Date: 2024-07-24 14:50:39.102847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1980e6cf9a0f'
down_revision: Union[str, None] = 'ebc72e5e4b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_types')
    op.drop_table('job_status')
    # ### end Alembic commands ###
